function SeqObj(n){this.n=n-1||0;this.nInit=this.n;this.next=function(){return++this.n};this.curr=function(){return this.n};this.reset=function(){this.n=this.nInit}}
var csvRedQuery;function temGetVal(oCsv,s,rownum,seq){oCsv=oCsv||CSV;var j,k;var rn=rownum+1;var nr=oCsv.table.length;var nh=oCsv.arHeaderRow.length;var nf=0;var br="\n";var lb="{";var rb="}";var tab="    ";for(k=0;k<oCsv.maxColumnsFound;k++){eval("var f"+(k+1)+"=''");eval("var h"+(k+1)+"=''")}
for(k=0;k<oCsv.arHeaderRow.length;k++){eval("var h"+(k+1)+"=oCsv.arHeaderRow[k]")}
if(rownum>=0){for(k=0;k<oCsv.table[rownum].length;k++){eval("var f"+(k+1)+"=oCsv.table[rownum][k]")}}
nf=(rownum>=0)?oCsv.table[rownum].length:0;var a=s.split('.');var b;for(j=0;j<a.length;j++){b=a[j].trim().split('(');if(b[0].trim().toLowerCase()=='csv'&&b.length>1&&b[1].trim()===')'){a[j]="csv("+oCsv.quote.enclose('"','\\')+","+oCsv.quote.enclose('"','\\')+")"}}
try{return eval(a.join('.'))}catch(e){return ""}}
function temHandler(oCsv,tem,rownum,seq){oCsv=oCsv||CSV;if(tem.trim()=="")return tem;tem=tem.replace(/\r\n|\r|\n/g,"{br}").replace(/{\s/g,"{lb} ").replace(/{$/g,"{lb}").replace(/\s}/g," {rb}").replace(/^}/g,"{rb}");var a=tem.replace(/{/g,'{\n').split(/{|}/);var s=a.join('\n');var j=0;var cmd=false;lines=s.split("\n");var t=[];while(j<lines.length){if(cmd&&lines[j]!=""){t.push(temGetVal(oCsv,lines[j],rownum,seq));cmd=false}else if(lines[j]==""){cmd=true}else{t.push(lines[j])}
j++}
return t.join('')}
function csvFromTem(oCsv,temHead,tem,temBetween,temFoot,temCond){var j;var v;oCsv=oCsv||CSV;var s="";var seqobj=new SeqObj();s+=temHandler(oCsv,temHead,-1,0);for(j=0;j<oCsv.table.length;j++){v=temHandler(oCsv,temCond,j,j);if(v.toString().left(5)=="false")continue;s+=temHandler(oCsv,tem,j,seqobj.next());if(j!=oCsv.table.length-1)s+=temHandler(oCsv,temBetween,j,seqobj.curr())}
s+=temHandler(oCsv,temFoot,-1,seqobj.curr());return s}
function csvToTable(oCsv,addHeaderIfMissing,addLineNumbers,addSummary){var j,k,coltag;var s="<div class=\"row\"><div class=\"col-md-12\"><div class=\"panel panel-success\"><div class=\"panel-heading \"><h3 class=\"panel-title\">HTML Table Preview</h3></div>\n<table border=1 class=\"table table-striped table-bordered table-hover table-condensed\">\n";var a=[];var x=0;var v="";var sumFields=[];oCsv=oCsv||CSV;a=getFldPosArr(oCsv);for(k=0;k<oCsv.maxColumnsFound;k++)sumFields.push(0);if(oCsv.isFirstRowHeader||addHeaderIfMissing){s+="<thead><tr>";if(addLineNumbers)s+="<th>#</th>";for(x=0;x<a.length;x++){k=a[x]-1;if(k>oCsv.arHeaderRow.length)v="FIELD"+k;else v=oCsv.arHeaderRow[k];s+='<th title="Field #'+(k+1)+'">'+v.toHtml().replace(/\r\n|\r|\n/g,"<br/>")+"</th>\n"}
s+="</tr></thead>\n"}
s+="<tbody>";for(j=0;j<oCsv.table.length;j++){if(csvRedQuery&&csvRedQuery.query!=""){v=temHandler(oCsv,csvRedQuery.query,j,j);if(v.toString().left(5)=="false")continue}
s+="<tr>";if(addLineNumbers)s+="<td>"+(j+1)+"</td>\n";for(x=0;x<a.length;x++){k=a[x]-1;if(k>=oCsv.table[j].length)v=" ";else v=oCsv.table[j][k];if(oCsv.statsCnt[k]&&(oCsv.statsCnt[k].fieldType=="N"||oCsv.statsCnt[k].fieldType=="I")){s+="<td align=\"right\">"+v.toFixed(oCsv.statsCnt[k].fieldDecs)+"</td>\n";sumFields[k]+=1*v}else{if(v=="")v=" ";s+="<td>"+v.toHtml().replace(/\r\n|\n|\r/g,"<br/>")+"</td>\n"}}
s+="</tr>\n"}
s+="</tbody>";if(addSummary){s+="<tfoot><tr>";if(addLineNumbers)s+="<th>Sum</th>";for(x=0;x<a.length;x++){k=a[x]-1;if(oCsv.statsCnt[k]&&(oCsv.statsCnt[k].fieldType=="N"||oCsv.statsCnt[k].fieldType=="I")){s+="<th align=\"right\">"+sumFields[k].toFixed(oCsv.statsCnt[k].fieldDecs)+"</th>\n"}else{s+="<th>&nbsp;</th>"}}
s+="</tr></tfoot>\n"}
s+="</table>\n</div></div></div>";return s}
function csvToXml(oCsv,topName,rowName){var j=0,k,col;var hdr;var topLevel=topName||"ROWSET";var rowLevel=rowName||"ROW";var s="<?xml version=\"1.0\"?>\n<"+topLevel+">\n";var a=[];var x=0;var v="";var h="";oCsv=oCsv||CSV;a=getFldPosArr(oCsv);if(oCsv.table.length===0)return s+"</"+topLevel+">";hdr=getCsvHeader(oCsv);for(j=0;j<oCsv.table.length;j++){if(csvRedQuery&&csvRedQuery.query!=""){v=temHandler(oCsv,csvRedQuery.query,j,j);if(v.toString().left(5)=="false")continue}
s+="<"+rowLevel+">\n";for(x=0;x<a.length;x++){k=a[x]-1;if(k>=oCsv.table[j].length)v="";else v=oCsv.table[j][k]+"";if(k>=hdr.length)h="FIELD"+k;else h=hdr[k];s+="<"+h.replace(/\s+/g,'_')+">"+v.toXml()+"</"+h.replace(/\s+/g,'_')+">\n"}
s+="</"+rowLevel+">\n"}
s+="</"+topLevel+">";return s}
function csvToXmlProperties(oCsv,topName,rowName){var j=0,k,col;var hdr;var topLevel=topName||"ROWSET";var rowLevel=rowName||"ROW";var s="<?xml version=\"1.0\"?>\n<"+topLevel+">\n";var a=[];var x=0;var v="";var h="";oCsv=oCsv||CSV;a=getFldPosArr(oCsv);if(oCsv.table.length===0)return s+"</"+topLevel+">";hdr=getCsvHeader(oCsv);for(j=0;j<oCsv.table.length;j++){if(csvRedQuery&&csvRedQuery.query!=""){v=temHandler(oCsv,csvRedQuery.query,j,j);if(v.toString().left(5)=="false")continue}
s+="<"+rowLevel;for(x=0;x<a.length;x++){k=a[x]-1;if(k>=oCsv.table[j].length)v="";else v=oCsv.table[j][k];if(k>=hdr.length)h="FIELD"+k;else h=hdr[k];s+=" "+h.replace(/\s+/g,'_')+'="'+(v+"").toXml()+'"'}
s+="></"+rowLevel+">\n"}
s+="</"+topLevel+">";return s}
function csvToJSON(oCsv,forceWrap){var j=0,k,col;var hdr;var s="[\n";var a=[];var x=0;var v="";var h="";oCsv=oCsv||CSV;a=getFldPosArr(oCsv);if(oCsv.table.length===0)return s+"]";hdr=getCsvHeader(oCsv);for(j=0;j<oCsv.table.length;j++){if(csvRedQuery&&csvRedQuery.query!=""){v=temHandler(oCsv,csvRedQuery.query,j,j);if(v.toString().left(5)=="false")continue}
s+="  {\n";for(x=0;x<a.length;x++){k=a[x]-1;if(k>=oCsv.table[j].length)v="";else v=oCsv.table[j][k];if(k>=hdr.length||!hdr[k]||hdr[k]==""){h="FIELD"+(x+1)}else{h=hdr[k]}
s+='    "'+h.toJson()+'":';if(!forceWrap&&oCsv.statsCnt[k]&&(oCsv.statsCnt[k].fieldType=="N"||oCsv.statsCnt[k].fieldType=="I")){if(v!=""){v=v.toNumber()+"";if(v.left(1)==".")v="0"+v;if(v.left(2)=="-.")v="-0"+v.substr(1);s+=v}else s+='null'}else{s+='"'+v.toJson()+'"'}
s+=(x<a.length-1?',':'')+"\n"}
s+="  }";if(j<oCsv.table.length-1)s+=",";s+="\n"}
s+="]";return s}
function csvToJSONArray(oCsv,forceWrap){var j=0,k,col;var hdr;var s="[\n";var a=[];var x=0;var v="";var h="";oCsv=oCsv||CSV;a=getFldPosArr(oCsv);if(oCsv.table.length===0)return s+"]";hdr=getCsvHeader(oCsv);for(j=0;j<oCsv.table.length;j++){if(csvRedQuery&&csvRedQuery.query!=""){v=temHandler(oCsv,csvRedQuery.query,j,j);if(v.toString().left(5)=="false")continue}
if(a.length>1){s+="  ["}
for(x=0;x<a.length;x++){k=a[x]-1;if(k>=oCsv.table[j].length)v="";else v=oCsv.table[j][k];if(k>=hdr.length)h="FIELD"+k;else h=hdr[k];if(!forceWrap&&oCsv.statsCnt[k]&&(oCsv.statsCnt[k].fieldType=="N"||oCsv.statsCnt[k].fieldType=="I")){if(v!=""){v=v.toNumber()+"";if(v.left(1)==".")v="0"+v;if(v.left(2)=="-.")v="-0"+v.substr(1);s+=v}else s+='null'}else{s+='"'+v.toJson()+'"'}
s+=(x<a.length-1?',':'')}
if(a.length>1){s+="  ]"}
if(j<oCsv.table.length-1)s+=",";s+="\n"}
s+="]";return s}
function csvToJSONColumnArray(oCsv,forceWrap){var j=0,k,col;var hdr;var s="{\n";var a=[];var x=0;var v="";var h="";oCsv=oCsv||CSV;a=getFldPosArr(oCsv);if(oCsv.table.length===0)return s+"]";hdr=getCsvHeader(oCsv);for(x=0;x<a.length;x++){k=a[x]-1;if(x>=hdr.length)h="FIELD"+k;else h=hdr[k];s+='    "'+h+'":[';var crow=0;for(j=0;j<oCsv.table.length;j++){if(csvRedQuery&&csvRedQuery.query!=""){v=temHandler(oCsv,csvRedQuery.query,j,j);if(v.toString().left(5)=="false")continue}
crow++;s+=(crow>1?',':'');if(x>=oCsv.table[j].length)v="";else v=oCsv.table[j][k];if(!forceWrap&&oCsv.statsCnt[k]&&(oCsv.statsCnt[k].fieldType=="N"||oCsv.statsCnt[k].fieldType=="I")){if(v!=""){v=v.toNumber()+"";if(v.left(1)==".")v="0"+v;if(v.left(2)=="-.")v="-0"+v.substr(1);s+=v}else s+='null'}else{s+='"'+v.toJson()+'"'}}
s+="]";if(x<a.length-1)s+=",";s+="\n"}
s+="}";return s}
function jsonToCsv(objArray,delimiter,bIncludeHeaders,bQuotes,noMultiLines){var array;var str='';var line='';var i,j;var index;var value;var columns=[];try{array=typeof objArray!='object'?JSON.parse(objArray):objArray}catch(e){array=eval("array="+objArray)}
var depth=getJsonLevel(array);if((depth==2)&&(_.isArray(array))){if(bIncludeHeaders){value='Field1';if(bQuotes)line+='"'+value.replace(/"/g,'""')+'"'+delimiter;else line+=value.toCsv(delimiter,'"');str+=line+'\n'}
for(i=0;i<array.length;i++){var line='';value=array[i];if(value==null)value="";else value+="";if(noMultiLines)value=value.replace(/\r\n|\r|\n/g,' ');line+=(bQuotes?'"':"")+(""+value).toCsv(delimiter,'"')+(bQuotes?'"':"");str+=line+'\n'}
return str}
if((depth==3)&&(_.isArray(array))&&(_.every(_.values(array),_.isArray))){if(bIncludeHeaders){var head=array[0];for(index in array[0]){value='Field'+(index*1+1);columns.push(value);if(bQuotes)line+='"'+value.replace(/"/g,'""')+'"'+delimiter;else line+=value.toCsv(delimiter,'"')+delimiter}
line=line.slice(0,-1);str+=line+'\n'}else{for(index in array[0])columns.push(index)}
for(i=0;i<array.length;i++){var line='';for(j=0;j<columns.length;j++){value=array[i][j];if(value==null)value="";else value+="";if(noMultiLines)value=value.replace(/\r\n|\r|\n/g,' ');line+=(bQuotes?'"':"")+(""+value).toCsv(delimiter,'"')+(bQuotes?'"':"")+delimiter}
line=line.slice(0,-1*delimiter.length);str+=line+'\n'}
return str}
for(;;){if(_.isObject(array)&&!(_.isArray(array))&&_.keys(array).length==1&&(_.isObject(_.values(array)[0])||(_.isArray(_.values(array)[0])&&_.isObject(_.values(array)[0][0])))){array=_.values(array)[0]}else break}
if(_.isArray(array)==false&&_.isObject(array)==true){array=JSON.flatten(array);array=JSON.parse('['+JSON.stringify(array)+']')}
for(i=0;i<array.length;i++){value=array[i][columns[j]];if(_.isArray(value)==false&&_.isObject(value)==true){array[i][columns[j]]=JSON.flatten(value)}}
if(bIncludeHeaders){var head=array[0];if(bQuotes){for(index in array[0]){value=index+"";columns.push(value);line+='"'+value.replace(/"/g,'""')+'"'+delimiter}}else{for(index in array[0]){value=index+"";columns.push(value);line+=value.toCsv(delimiter,'"')+delimiter}}
line=line.slice(0,-1);str+=line+'\n'}else{for(index in array[0])columns.push(index)}
for(i=0;i<array.length;i++){var line='';if(bQuotes){for(j=0;j<columns.length;j++){value=array[i][columns[j]];if((value+"").substring(0,15)=="[object Object]")value=JSON.valueArray(array[i][columns[j]]).slice(0,-1);if(value==null)value="";else value+="";if(noMultiLines)value=value.replace(/\r\n|\r|\n/g,' ');line+='"'+value.replace(/"/g,'""')+'"'+delimiter}}else{for(j=0;j<columns.length;j++){value=array[i][columns[j]];if((value+"").substring(0,15)=="[object Object]")value=JSON.valueArray(array[i][columns[j]]).slice(0,-1);if(value==null)value="";else value+="";if(noMultiLines)value=value.replace(/\r\n|\r|\n/g,' ');line+=(""+value).toCsv(delimiter,'"')+delimiter}}
line=line.slice(0,-1*delimiter.length);str+=line+'\n'}
return str}
function csvToFixed(oCsv,addsep,addTable,addLineNumbers,addRuler,addLineSep){var j=0,k,col;var s="";var a=[];var x=0;var v="";var ruler="";var ruler10="";a=getFldPosArr(oCsv);var centerAdjust=false;var rightAdjust=false;if(typeof addsep==='undefined'||addsep==null)addsep=" ";if(addTable&&(addsep===""||addsep===" "))addsep="|";oCsv=oCsv||CSV;if(oCsv.table.length===0)return s;var hdr=getCsvHeader(oCsv);var stats=getCsvColLength(oCsv);var linewidth=0;var rulerSize=0;var rulerdash="";if(addTable){for(x=0;x<a.length;x++){k=a[x]-1;if(oCsv.isFirstRowHeader&&hdr[k]&&hdr[k].length>stats[k])stats[k]=hdr[k].length;linewidth+=stats[k]+1}
if(addLineNumbers)linewidth+=(""+oCsv.table.length).length+1;s+="+".rpad(linewidth,"-")+"+\n";if(oCsv.isFirstRowHeader){s+=addsep;if(addLineNumbers)s+="#".rpad((""+oCsv.table.length).length)+addsep;for(x=0;x<a.length;x++){k=a[x]-1;if(x>0)s+=addsep;if(k>=hdr.length)v="";else v=hdr[k].replace(/\r\n|\r|\n/g,' ');s+=v.rpad(stats[k])}
s+=addsep+"\n";s+="+".rpad(linewidth,"-")+"+\n"}}
var crow=0;for(j=0;j<oCsv.table.length;j++){if(csvRedQuery&&csvRedQuery.query!=""){v=temHandler(oCsv,csvRedQuery.query,j,j);if(v.toString().left(5)=="false")continue}
crow++;if(addTable)s+=addsep;if(addLineNumbers)s+=(""+crow).rpad((""+oCsv.table.length).length)+addsep;for(x=0;x<a.length;x++){k=a[x]-1;if(x>0)s+=addsep;if(k>=oCsv.table[j].length)v="";else v=oCsv.table[j][k];rightAdjust=false;centerAdjust=false;if(document.getElementById("ftrim"+(k+1)))if(document.getElementById("ftrim"+(k+1)).checked)v=v.trim();if(document.getElementById("chkupper"+(k+1)))if(document.getElementById("chkupper"+(k+1)).checked)v=v.toUpperCase();if(document.getElementById("chklower"+(k+1)))if(document.getElementById("chklower"+(k+1)).checked)v=v.toLowerCase();if(document.getElementById("chkrjust"+(k+1)))if(document.getElementById("chkrjust"+(k+1)).checked)rightAdjust=true;if(document.getElementById("chkcjust"+(k+1)))if(document.getElementById("chkcjust"+(k+1)).checked)centerAdjust=true;if(centerAdjust)s+=v.replace(/\r\n|\r|\n/g,' ').cjust(stats[k]);else if(rightAdjust)s+=v.replace(/\r\n|\r|\n/g,' ').rjust(stats[k]);else s+=v.replace(/\r\n|\r|\n/g,' ').rpad(stats[k])}
var z;if(!addTable&&addRuler&&crow==1){for(z=1;z<=s.length;z++){ruler+=(""+z).right(1)}
if(s.length>=10){for(z=1,x=10;x<=s.length;x+=10,z++){ruler10+="         "+(""+z).right(1)}
ruler10=ruler10.rpad(ruler.length);ruler=ruler10+"\n"+ruler}}
if(addTable)s+=addsep;s+="\n";if(addTable&&addLineSep)s+="+".rpad(linewidth,"-")+"+\n"}
if(addTable&&!addLineSep)s+="+".rpad(linewidth,"-")+"+\n";if(addRuler&&!addTable){rulerdash=ruler.split("\n")[1].replace(/[12346789]/g,"-").replace(/0/g,'|').replace(/5/g,'+');s=ruler+"\n"+rulerdash+"\n"+s}
return s}
function fixedToCsv(input,fieldDef,delimiter,bIncludeHeaders,bQuotes){var fa=fieldDef.split('|')||[];var str='';var line='';var fld=[];var header="";var array=input.split(/\n|\r|\r\n/gmi);var i,j;if(array[array.length-1]=="")array.pop();if(bIncludeHeaders){for(i=0;i<fa.length;i++){fld=fa[i].split(',');if(fld.length>2)header=fld[2];else header="F"+(i+1);if(bQuotes){str+='"'+header.replace(/"/g,'""')+'"'+delimiter}else{str+=header.toCsv(delimiter,'"')+delimiter}}
str=str.slice(0,-1*delimiter.length)+"\n"}
var p=0;var len=0;var head="";for(i=0;i<array.length;i++){line="";if(array[i]=="")continue;for(j=0;j<fa.length;j++){fld=fa[j].split(',')||[];if(fld.length>0)p=fld[0]-1;else p=0;if(fld.length>1)len=fld[1];else len=0;if(fld.length>2)head=fld[2];else head="f"+(j+1);value=array[i].substr(p,len).trim();if(value==null)value="";else value+="";if(bQuotes){line+='"'+(""+value).replace(/"/g,'""')+'"'+delimiter}else{line+=(""+value).toCsv(delimiter,'"')+delimiter}}
line=line.slice(0,-1*delimiter.length);str+=line+'\n'}
return str}
function csvToMulti(oCsv,sep,addFieldName,addFieldNameSep,addLineAfterField,addXSpaces){var j=0,k,col;var hdr;var s="";var a=[];var x=0;var v="";var fheader="";addXSpaces=addXSpaces||"0";if(isNaN("0"+addXSpaces))addXSpaces="0";a=getFldPosArr(oCsv);oCsv=oCsv||CSV;addFieldNameSep=addFieldNameSep||'';if(oCsv.table.length===0)return s;hdr=getCsvHeader(oCsv);for(j=0;j<oCsv.table.length;j++){if(csvRedQuery&&csvRedQuery.query!=""){v=temHandler(oCsv,csvRedQuery.query,j,j);if(v.toString().left(5)=="false")continue}
for(x=0;x<a.length;x++){fheader="";k=a[x]-1;if(k>=oCsv.table[j].length)v="";else v=oCsv.table[j][k].replace(/\r\n|\r|\n/g,' ');if(addFieldName){if(k>=oCsv.arHeaderRow.length)fheader="".rpad(addXSpaces)+"Field-"+(k+1)+addFieldNameSep;else fheader="".rpad(addXSpaces)+oCsv.arHeaderRow[k].replace(/\r\n|\r|\n/g,' ')+addFieldNameSep}
s+=fheader+v+"\n";if(addLineAfterField)s+="\n"}
s+=sep+"\n"}
return s}
function csvToKml(oCsv,nameCol,descCol,latCol,longCol,descCol2){var j=0,k,col;var hdr;var desc2="";var s="<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";s+="<kml xmlns=\"http://earth.google.com/kml/2.0\">\n";s+="<Document>\n";oCsv=oCsv||CSV;if(oCsv.table.length===0)return s+"</Document></kml>";hdr=getCsvHeader(oCsv);if(descCol2.trim()==""||isNaN(descCol2)||(descCol2*1<1||descCol2*1>oCsv.table[0].length)){descCol2=""}
for(j=0;j<oCsv.table.length;j++){if(csvRedQuery&&csvRedQuery.query!=""){v=temHandler(oCsv,csvRedQuery.query,j,j);if(v.toString().left(5)=="false")continue}
s+="<Placemark>\n";desc2="";for(k=0;k<oCsv.table[j].length;k++){if(k>=hdr.length)break;if(!isNaN(latCol)&&k==(latCol-1))continue;if(!isNaN(longCol)&&k==(longCol-1))continue;if(!isNaN(nameCol)&&k==(nameCol-1))hdr[k]="name";else if(!isNaN(descCol)&&k==(descCol-1)){hdr[k]="description";if(descCol2!="")desc2=" "+oCsv.table[j][descCol2-1]}else continue;s+="<"+hdr[k]+">"+oCsv.table[j][k].toHtml()+desc2.toHtml()+"</"+hdr[k]+">\n"}
if(!isNaN(latCol)&&!isNaN(longCol)&&latCol.length>0&&longCol.length>0&&latCol*1<=oCsv.table[j].length&&longCol*1<=oCsv.table[j].length&&oCsv.table[j][latCol*1-1]&&oCsv.table[j][longCol*1-1]){s+="<Point><coordinates>";s+=oCsv.table[j][longCol*1-1]+","+oCsv.table[j][latCol*1-1]+",0";s+="</coordinates></Point>\n"}
s+="</Placemark>\n"}
s+="</Document>\n</kml>";return s}
function csvToCsv(oCsv,delimiter,headingSpecified,excelForceMode,defaultHeader,noMultiLines,bQuotes){oCsv=oCsv||CSV;if(oCsv.table.length===0)return "";var j=0,k,col;var hdr;var s="";var a=[];var x=0;var v;a=getFldPosArr(oCsv);if(headingSpecified||defaultHeader){hdr=getCsvHeader(oCsv);for(x=0;x<a.length;x++){j=a[x]-1;if(x>0)s+=delimiter;s+=(j>=hdr.length?"":hdr[j]).toCsv(delimiter,oCsv.quote)}
if(s!="")s+="\n"}
for(j=0;j<oCsv.table.length;j++){if(csvRedQuery&&csvRedQuery.query!=""){v=temHandler(oCsv,csvRedQuery.query,j,j);if(v.toString().left(5)=="false")continue}
for(x=0;x<a.length;x++){k=a[x]-1;v=oCsv.table[j][k]?oCsv.table[j][k]:"";if(v&&noMultiLines)v=v.replace(/\r\n|\r|\n/g,' ');if(excelForceMode&&v!=""){if(v.indexOf(',')<0){s+="="+v.toCsv(delimiter,oCsv.quote,oCsv.quote,excelForceMode)}else{s+='"="'+v.toCsv(delimiter,oCsv.quote,oCsv.quote,excelForceMode)+'""'}}else if(!bQuotes&&oCsv.statsCnt[k]&&(oCsv.statsCnt[k].fieldType=="N"||oCsv.statsCnt[k].fieldType=="I")){if(v)s+=v;else s+=''}else{s+=v.toCsv(delimiter,oCsv.quote,oCsv.quote,bQuotes)}
s+=(x<a.length-1?delimiter:'')}
s+="\n"}
return s}
function transposeCsv(oCsv,delimiter,headingSpecified,excelForceMode,defaultHeader,noMultiLines,bQuotes){oCsv=oCsv||CSV;if(oCsv.table.length===0)return "";var j=0,k,col;var hdr;var s="";var a=[];var x=0;var v;a=getFldPosArr(oCsv);for(x=0;x<a.length;x++){if(headingSpecified||defaultHeader){hdr=getCsvHeader(oCsv);j=a[x]-1;s+=(hdr[j]).toCsv(delimiter,oCsv.quote);if(oCsv.table.length>0)s+=delimiter}
for(j=0;j<oCsv.table.length;j++){if(csvRedQuery&&csvRedQuery.query!=""){v=temHandler(oCsv,csvRedQuery.query,j,j);if(v.toString().left(5)=="false")continue}
k=a[x]-1;v=oCsv.table[j][k]?oCsv.table[j][k]:"";if(v&&noMultiLines)v=v.replace(/\r\n|\r|\n/g,' ');v=doTransformations(v,k,oCsv);if(excelForceMode&&v!=""){if(v.indexOf(',')<0){s+="="+v.toCsv(delimiter,oCsv.quote,oCsv.quote,excelForceMode)}else{s+='"="'+v.toCsv(delimiter,oCsv.quote,oCsv.quote,excelForceMode)+'""'}}else if(!bQuotes&&oCsv.statsCnt[k]&&(oCsv.statsCnt[k].fieldType=="N"||oCsv.statsCnt[k].fieldType=="I")){if(v)s+=v;else s+=''}else{s+=v.toCsv(delimiter,oCsv.quote,oCsv.quote,bQuotes)}
s+=(j<oCsv.table.length-1?delimiter:'')}
s+="\n"}
return s}
function getCsvColLength(oCsv){var j=0,k=0;var n=0;var stats=new Array();oCsv=oCsv||CSV;if(oCsv.table.length===0)return stats;for(k=0;k<oCsv.maxColumnsFound;k++)stats.push(0);for(j=0;j<oCsv.table.length;j++){for(k=0;k<stats.length;k++){if(k>=oCsv.table[j].length)continue;if(oCsv.table[j][k].length>stats[k])stats[k]=oCsv.table[j][k].length;if(document.getElementById('fpadsize'+(k+1))){n=document.getElementById('fpadsize'+(k+1)).value;if(isNaN(n))n=0;else n=n*1;if(n>stats[k])stats[k]=n}}}
return stats}
function isSqlKeywords(){return["ACTION","ADD","AFTER","ALL","ALTER","ANALYZE","AND","AS","ASC","ATTACH","AUTOINCREMENT","BEFORE","BEGIN","BETWEEN","BY","CASCADE","CASE","CAST","CHECK","COLLATE","COLUMN","COMMIT","CONFLICT","CONSTRAINT","CREATE","CROSS","CURRENT_DATE","CURRENT_TIME","CURRENT_TIMESTAMP","DATABASE","DEFAULT","DEFERRABLE","DEFERRED","DELETE","DESC","DETACH","DISTINCT","DROP","EACH","ELSE","END","ESCAPE","EXCEPT","EXCLUSIVE","EXISTS","EXPLAIN","FAIL","FOR","FOREIGN","FROM","FULL","GLOB","GROUP","HAVING","IF","IGNORE","IMMEDIATE","IN","INDEX","INDEXED","INITIALLY","INNER","INSERT","INSTEAD","INTERSECT","INTO","IS","ISNULL","JOIN","KEY","LEFT","LIKE","LIMIT","MATCH","NATURAL","NO","NOT","NOTNULL","NULL","OF","OFFSET","ON","OR","ORDER","OUTER","PLAN","PRAGMA","PRIMARY","QUERY","RAISE","RECURSIVE","REFERENCES","REGEXP","REINDEX","RELEASE","RENAME","REPLACE","RESTRICT","RIGHT","ROLLBACK","ROW","SAVEPOINT","SELECT","SET","SUM","SYSDATE","TABLE","TEMP","TEMPORARY","THEN","TO","TRANSACTION","TRIGGER","UNION","UNIQUE","UPDATE","USING","VACUUM","VALUES","VIEW","VIRTUAL","WHEN","WHERE","WITH","WITHOUT"]}
function csvToSql(oCsv,tabname,operation,newlines,createTable,createNotExists,dropTable,dropExists,useReplace,insertText,useTerseValues,useNullAsNull){var j=0,k,col,n,m,d;var hdr;var s="";var tp="";var seqtype="";var v="";var tem="";var cv="";var incl=[];var usrhdr=[];var fsize=[];var fdec=[];var freq=[];var where="";var keys=[];var keycnt=0;oCsv=oCsv||CSV;if(oCsv.table.length===0)return s;operation=operation||"I";newlines=newlines||false;hdr=getCsvHeader(oCsv);for(n=k=0;k<hdr.length;k++){usrhdr[k]=hdr[k].replace(/\s+/g,'_');keys[k]=false;fsize[k]=fdec[k]="";if(document.getElementById("fkey"+(k+1)))if(document.getElementById("fkey"+(k+1)).checked){keycnt++;keys[k]=true}
if(document.getElementById("fname"+(k+1)))usrhdr[k]=document.getElementById("fname"+(k+1)).value.replace(/\s+/g,'_');if(document.getElementById("freq"+(k+1)))freq[k]=(document.getElementById("freq"+(k+1))).checked;if(document.getElementById("fsize"+(k+1))){fsize[k]=document.getElementById("fsize"+(k+1)).value.trim();if(!isNaN(fsize[k]))fsize[k]*=1;else fsize[k]=30;if(fsize[k]<1)fsize[k]=""}else fsize[k]=30;if(document.getElementById("fdec"+(k+1))){fdec[k]=document.getElementById("fdec"+(k+1)).value.trim();if(!isNaN(fdec[k])){fdec[k]*=1;if(fdec[k]<0)fdec[k]=""}else{fdec[k]=""}}
if(document.getElementById("finc"+(k+1))){if(document.getElementById("finc"+(k+1)).checked){incl[k]=true;n++}else{incl[k]=false}}else{incl[k]=true;n++}}
if(n==0)return "";if(tabname.indexOf(' ')>0)tabname='"'+tabname+'"';if(dropTable)s+="DROP TABLE "+(dropExists?"IF EXISTS ":"")+tabname+";\n";if(createTable){var savnewlines=newlines;newlines=true;s+="CREATE TABLE "+(createNotExists?"IF NOT EXISTS ":"")+tabname+"(";if(newlines)s+="\n";for(n=k=0;k<hdr.length;k++,n++){if(newlines&&n>0)s+="\n";if(n>0)s+=",";else s+=" ";s+=" "+usrhdr[k];tp=oCsv.statsCnt[k].fieldType;if(document.getElementById("ftype"+(k+1))){tp=document.getElementById("ftype"+(k+1)).value}
switch(tp){case "B":s+=" BIT ";break;case "NR":case "N":if(tp=="N")s+=" NUMERIC";else s+=" NUMBER";m=oCsv.statsCnt[k].fieldPrec+oCsv.statsCnt[k].fieldDecs;d=oCsv.statsCnt[k].fieldDecs;if(fsize[k]&&fsize[k]>m)m=fsize[k];if(m!="")s+="("+m+","+d+")";else s+=" ";break;case "IT":s+=" INT ";break;case "I":s+=" INTEGER";m=fsize[k];if(m!=""){s+="("+m+")"}else s+=" ";break;case "S":s+=" SERIAL ";break;case "D":s+=" DATE ";break;case "DT":s+=" DATETIME ";break;case "VC":s+=" VARCHAR("+fsize[k]+")";break;default:s+=" CHAR("+fsize[k]+")";break}
if(freq[k])s+=" NOT NULL";if(keys[k]&&keycnt==1){s+=" PRIMARY KEY";if(tp=="N"||tp=="NR"||tp=="I"||tp=="IT"){if(document.getElementById('selAutoIncrement')){s+=" "+document.getElementById('selAutoIncrement').value}}}}
if(keycnt>1){if(newlines)s+="\n";s+=", PRIMARY KEY(";for(x=0;x<keys.length;x++){if(keys[x]){s+=((x>0)?",":"")+usrhdr[x]}}
s+=")"}
if(newlines)s+="\n";s+=");\n";newlines=savnewlines}
switch(operation){case "I":for(j=0;j<oCsv.table.length;j++){if(csvRedQuery&&csvRedQuery.query!=""){v=temHandler(oCsv,csvRedQuery.query,j,j);if(v.toString().left(5)=="false")continue}
if(j==0||!useTerseValues){s+=useReplace?"REPLACE":"INSERT";if(insertText.trim()!="")s+=" "+insertText.trim();s+=" INTO "+tabname+"(";if(newlines)s+="\n";for(n=k=0;k<hdr.length;k++){if(!incl[k])continue;if(n>0)s+=",";s+=usrhdr[k];if(newlines)s+="\n";n++}
s+=") VALUES"+(!useTerseValues?"":"\n")+" ("}else{s+=",("}
if(newlines)s+="\n";for(n=k=0;k<hdr.length;k++){if(!incl[k])continue;tp=oCsv.statsCnt[k].fieldType;if(k>=oCsv.table[j].length){v=""}else{v=oCsv.table[j][k]}
if(document.getElementById("ftype"+(k+1))){tp=document.getElementById("ftype"+(k+1)).value}
if(document.getElementById("ftem"+(k+1)))tem=document.getElementById("ftem"+(k+1)).value;if(document.getElementById("ftrim"+(k+1)))if(document.getElementById("ftrim"+(k+1)).checked)v=v.trim();if(document.getElementById("chkupper"+(k+1)))if(document.getElementById("chkupper"+(k+1)).checked)v=v.toUpperCase();if(document.getElementById("chklower"+(k+1)))if(document.getElementById("chklower"+(k+1)).checked)v=v.toLowerCase();if(n>0)s+=",";if(tem!=""){if(tp=='N'||tp=="NR"||tp=='I'||tp=="IT"||tp=="S"||tp=="D"||tp=="DT"){if(v=="")s+=tem.replace("{f}",'NULL');else if(tp=="D"||tp=="DT")s+=tem.replace("{f}","'"+v.toSql()+"'");else s+=tem.replace("{f}",v.toSql())}else{s+=tem.replace("{f}","'"+v.toSql()+"'")}}else{switch(tp){case "B":case "NR":case "S":case "N":case "IT":case "I":if((v.trim()==="")||(v.toUpperCase()=="NULL"&&useNullAsNull))s+="NULL";else s+=v.toSql();break;case "DT":case "D":if((v==="")||(v.toUpperCase()=="NULL"&&useNullAsNull))s+="NULL";else s+="'"+v.toSql()+"'";break;default:if(v.toUpperCase()=="NULL"&&useNullAsNull){s+="NULL"}else{s+="'"+v.toSql()+"'"}
break}}
if(newlines)s+="\n";n++}
if(!useTerseValues||j==oCsv.table.length-1){s+=");\n"}else{s+=")\n"}}
break;case "U":for(j=0;j<oCsv.table.length;j++){if(csvRedQuery&&csvRedQuery.query!=""){v=temHandler(oCsv,csvRedQuery.query,j,j);if(v.toString().left(5)=="false")continue}
where="1=1";s+="UPDATE";if(insertText.trim()!="")s+=" "+insertText.trim();s+=" "+tabname+" SET ";if(newlines)s+="\n";for(k=0;k<hdr.length;k++){if(keys[k])where+=" AND "+usrhdr[k]+"= {f"+k+"}"}
if(where==="1=1")where+=" AND "+usrhdr[0]+"= {f0}";for(n=k=0;k<hdr.length;k++){if(incl[k]){if(n>0)s+=",";s+=usrhdr[k]+" = ";n++}
tp=oCsv.statsCnt[k].fieldType;if(k>=oCsv.table[j].length)v="";else v=oCsv.table[j][k];if(document.getElementById("ftype"+(k+1)))tp=document.getElementById("ftype"+(k+1)).value;if(document.getElementById("ftem"+(k+1)))tem=document.getElementById("ftem"+(k+1)).value;if(document.getElementById("ftrim"+(k+1)))if(document.getElementById("ftrim"+(k+1)).checked)v=v.trim();if(document.getElementById("chkupper"+(k+1)))if(document.getElementById("chkupper"+(k+1)).checked)v=v.toUpperCase();if(document.getElementById("chklower"+(k+1)))if(document.getElementById("chklower"+(k+1)).checked)v=v.toLowerCase();if(tem!=""){if(v==""&&(tp=='N'||tp=="NR"||tp=='I'||tp=="IT"||tp=='D')){s+=tem.replace("{f}",'NULL')}else{s+=tem.replace("{f}",v.toSql())}}
switch(tp){case "B":if(incl[k])s+="'"+v.toSql()+"'";where=where.replace("{f"+k+"}","'"+v.toSql()+"'");break;case "NR":case "N":if(incl[k]){if((v==="")||(v.toUpperCase()=="NULL"&&useNullAsNull))s+="NULL";else s+=v.toSql()}
where=where.replace("{f"+k+"}",v.toSql());break;case "IT":case "I":if(incl[k]){if((v==="")||(v.toUpperCase()=="NULL"&&useNullAsNull))s+="NULL";else s+=v.toSql()}
where=where.replace("{f"+k+"}",v.toSql());break;case "D":if(incl[k]){if((v==="")||(v=="NULL"&&useNullAsNull))s+="NULL";else s+="'"+v.toSql()+"'"}
where=where.replace("{f"+k+"}","'"+v.toSql()+"'");break;default:if(incl[k]){if(v.toUpperCase()=="NULL"&&useNullAsNull){s+="NULL"}else{s+="'"+v.toSql()+"'"}}
where=where.replace("{f"+k+"}","'"+v.toSql()+"'");break}
if(incl[k]){if(newlines)s+="\n";n++}}
s+=" WHERE "+where;s+=";\n"}
break;case "D":for(j=0;j<oCsv.table.length;j++){if(csvRedQuery&&csvRedQuery.query!=""){v=temHandler(oCsv,csvRedQuery.query,j,j);if(v.toString().left(5)=="false")continue}
where="1=1";s+="DELETE FROM "+tabname;if(newlines)s+="\n";for(k=0;k<usrhdr.length;k++){if(keys[k])where+=" AND "+usrhdr[k]+"= {f"+k+"}"}
if(where==="1=1")where+=" AND "+usrhdr[0]+"= {f0}";for(n=k=0;k<hdr.length;k++){n++;tp=oCsv.statsCnt[k].fieldType;if(k>=oCsv.table[j].length)v="";else v=oCsv.table[j][k];if(document.getElementById("ftype"+(k+1)))tp=document.getElementById("ftype"+(k+1)).value;if(document.getElementById("ftem"+(k+1)))tem=document.getElementById("ftem"+(k+1)).value;if(document.getElementById("ftrim"+(k+1)))if(document.getElementById("ftrim"+(k+1)).checked)v=v.trim();if(document.getElementById("chkupper"+(k+1)))if(document.getElementById("chkupper"+(k+1)).checked)v=v.toUpperCase();if(document.getElementById("chklower"+(k+1)))if(document.getElementById("chklower"+(k+1)).checked)v=v.toLowerCase();if(tem!=""){}
switch(tp){case "B":case "NR":case "N":case "IT":case "S":case "I":where=where.replace("{f"+k+"}",v.toSql());break;default:where=where.replace("{f"+k+"}","'"+v.toSql()+"'");break}
if(newlines)s+="\n";n++}
s+=" WHERE "+where;s+=";\n"}
break}
return s}
function geoJsonToCsv(geo,delimiter,bIncludeHeaders,bQuotes,noMultiLines){var j;var s="";var value="";var cols={};var obj={};if(typeof geo==="string"){try{geo=JSON.parse(geo)}catch(e){geo=eval("geo="+geo)}}
var colnum=0;if(geo.type==="Feature"){geo={"type":"FeatureCollection","features":[geo]}}
if(geo.type==="FeatureCollection"){for(j=0;j<geo.features.length;j++){if(geo.features[j].geometry.type==="Point"){if(!("latitude"in cols))cols["latitude"]=++colnum;if(!("longitude"in cols))cols["longitude"]=++colnum}else{cols["coordinates"]=++colnum}
for(p in geo.features[j].properties){if(!(p in cols)){cols[p]=++colnum}}}
for(j=0;j<geo.features.length;j++){if("latitude"in cols){if(geo.features[j].geometry.type==="Point"){s+=(bQuotes?'"':"")+geo.features[j].geometry.coordinates[1]+(bQuotes?'"':"")+delimiter;s+=(bQuotes?'"':"")+geo.features[j].geometry.coordinates[0]+(bQuotes?'"':"")+delimiter}else{s+=(bQuotes?'""':"")+delimiter;s+=(bQuotes?'""':"")+delimiter}}
if("coordinates"in cols){if(geo.features[j].geometry.type!="Point"){value=geo.features[j].geometry.coordinates;if((value+"").substring(0,15)=="[object Object]")value=JSON.valueArray(value).slice(0,-1);s+=(""+value).toCsv(delimiter,'"','"',bQuotes)+delimiter}else{s+=(bQuotes?'""':"")+delimiter}}
for(p in cols){if(p=="latitude"||p==="longitude"||p==="coordinates")continue;if(p in geo.features[j].properties){value=geo.features[j].properties[p];if(value==null)value="";else value+="";if(noMultiLines)value=value.replace(/\r\n|\r|\n/g,' ');s+=value.toCsv(delimiter,'"','"',bQuotes)+delimiter}else{s+=(bQuotes?'""':"")+delimiter}}
s=s.slice(0,-1*delimiter.length)+"\n"}}
var t="";if(bIncludeHeaders){if("latitude"in cols){t+="latitude".toCsv(delimiter,'"','"',bQuotes)+delimiter}
if("longitude"in cols){t+="longitude".toCsv(delimiter,'"','"',bQuotes)+delimiter}
if("coordinates"in cols){t+="coordinates".toCsv(delimiter,'"','"',bQuotes)+delimiter}
for(p in cols){if(p=="latitude"||p==="longitude"||p==="coordinates")continue;t+=p.toCsv(delimiter,'"','"',bQuotes)+delimiter}
t=t.slice(0,-1*delimiter.length)+"\n"}
return t+s};function htmlEscape(str){return String(str).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/'/g,'&#39;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function getCsvHeader(oCsv){var k;var hdr=new Array();oCsv=oCsv||CSV;if(!oCsv)alert('Missing oCsv');if(!oCsv.arHeaderRow)alert('Missing arHeaderRow');var big=oCsv.arHeaderRow.length;if(big<oCsv.maxColumnsFound)big=oCsv.maxColumnsFound;for(k=0;k<big;k++){if(!oCsv.arHeaderRow[k])oCsv.arHeaderRow.push("FIELD"+(k+1));hdr.push(oCsv.arHeaderRow[k]);if(oCsv.headerToUpper){oCsv.arHeaderRow[k]=oCsv.arHeaderRow[k].toUpperCase();hdr[hdr.length-1]=hdr[hdr.length-1].toUpperCase()}else if(oCsv.headerToLower){oCsv.arHeaderRow[k]=oCsv.arHeaderRow[k].toLowerCase();hdr[hdr.length-1]=hdr[hdr.length-1].toLowerCase()}}
return hdr}
function sqlOptions(oCsv){oCsv=oCsv||CSV;var stats=getCsvColLength(oCsv);var hdr=getCsvHeader(oCsv);var s="<table>\n<tr>\n<th>Col #</th><th>Field Name</th><th>Data Type</th><th>Max Size</th><th title='# of decimals'>#<br/>Dec</th>";s+="<th>Key</th><th>Include</th><th>Required</th><th>Trim</th><th>Upper</th><th>Lower</th><th title=\"Modify output by using {f} for field value. Ex: {f}+100\">Template ({f}=field)<br/>Ex: {f}+100</th></tr>";var template="<tr><td>{#}</td>";template+="<td><input type=text id=\"fname{#}\" size=\"15\" value=\"{FIELDNAME{#}}\"></td>\n";template+="<td><select id=\"ftype{#}\" title=\"Choose data type of column\" >";template+="<option value=\"VC\" {VC{#}}>VarChar</option>";template+="<option value=\"C\" {C{#}}>Char</option>";template+="<option value=\"NR\" {NR{#}}>Number</option>";template+="<option value=\"N\" {N{#}}>Numeric</option>";template+="<option value=\"IT\" {IT{#}}>Int</option>";template+="<option value=\"I\" {I{#}}>Integer</option>";template+="<option value=\"D\" {D{#}}>Date</option>";template+="<option value=\"DT\" {DT{#}}>Date Time</option>";template+="<option value=\"B\" {B{#}}>Bit(0,1)</option>";template+="<option value=\"S\" {S{#}}>Serial</option>";template+="</select>\n</td><td><input id=\"fsize{#}\"size=4 maxlength=4 value=\"{FIELDSIZE{#}}\"></td>\n";template+="<td><input id=\"fdec{#}\"size=2 maxlength=2 value=\"{DECSIZE{#}}\" readonly></td>";template+="<td><input type=checkbox id=\"fkey{#}\"  value=\"Y\" ></td>\n";template+="<td><input type=checkbox id=\"finc{#}\"  value=\"Y\" checked></td>\n";template+="<td><input type=checkbox id=\"freq{#}\"  value=\"Y\" ></td>\n";template+="<td><input type=checkbox id=\"ftrim{#}\" value=\"Y\" checked></td>\n";template+="<td><input type=checkbox id=\"chkupper{#}\"  value=\"Y\" onclick=\"if(this.checked)document.getElementById('chklower{#}').checked=false\"></td>\n";template+="<td><input type=checkbox id=\"chklower{#}\"  value=\"Y\" onclick=\"if(this.checked)document.getElementById('chkupper{#}').checked=false\"></td>\n";template+="<td><input type=\"text\" id=\"ftem{#}\" value=\"\" size=\"15\" maxlength=\"200\"></td>";template+="</tr>";var j;for(j=0;j<hdr.length;j++){s+=template.replace(/{#}/g,""+(j+1)).replace("{FIELDNAME"+(j+1)+"}",hdr[j].replace(/[@+<>"'?\.,-\/#!$%\^&\*;:{}=\-`~()\[\]\\\|]/g,"").replace(/\s+/g,"_").replace(/_+/g,"_")).replace("{FIELDSIZE"+(j+1)+"}",(stats[j])==0?1:stats[j]);if(oCsv.statsCnt[j].fieldType==="N"){s=s.replace("{DECSIZE"+(j+1)+"}",oCsv.statsCnt[j].fieldDecs)}else{s=s.replace("{DECSIZE"+(j+1)+"}","")}
s=s.replace("ftitle"+(j+1)+"}","Type:"+oCsv.statsCnt[j].fieldType+",Counts: Total: "+oCsv.table.length+",Int: "+oCsv.statsCnt[j].intCnt+" ,Numeric:"+oCsv.statsCnt[j].realCnt+",Bit:"+oCsv.statsCnt[j].bitCnt+",Date:"+oCsv.statsCnt[j].dateCnt+",Empty:"+oCsv.statsCnt[j].emptyCnt);if(oCsv.statsCnt[j].fieldType==="VC")s=s.replace("{VC"+(j+1)+"}","selected");if(oCsv.statsCnt[j].fieldType==="C")s=s.replace("{C"+(j+1)+"}","selected");if(oCsv.statsCnt[j].fieldType==="N")s=s.replace("{N"+(j+1)+"}","selected");if(oCsv.statsCnt[j].fieldType==="I")s=s.replace("{I"+(j+1)+"}","selected");if(oCsv.statsCnt[j].fieldType==="B")s=s.replace("{B"+(j+1)+"}","selected");if(oCsv.statsCnt[j].fieldType==="D")s=s.replace("{D"+(j+1)+"}","selected");if(oCsv.statsCnt[j].fieldType==="S")s=s.replace("{S"+(j+1)+"}","selected")}
s+="</table>";return s}
function setOptions(oCsv){var j;oCsv=oCsv||CSV;var hdr=getCsvHeader(oCsv);if(document.getElementById('fkey1'))document.getElementById('fkey1').checked=true;if(document.getElementById('freq1'))document.getElementById('freq1').checked=true;for(j=0;j<hdr.length;j++){if(!document.getElementById('fname'+(j+1)))continue;document.getElementById('fname'+(j+1)).value=hdr[j].replace(/[@+<>"'?\.,-\/#!$%\^&\*;:{}=\-`~()\[\]\\\|]/g,"").replace(/\s+/g,"_").replace(/_+/g,"_");if(!document.getElementById('ftype'+(j+1)))continue;if(oCsv.statsCnt[j])continue;document.getElementById('ftype'+(j+1)).value=oCsv.statsCnt[j].fieldType;document.getElementById('ftype'+(j+1)).title="Type:"+oCsv.statsCnt[j].fieldType+",Counts: Total: "+oCsv.table.length+",Int: "+oCsv.statsCnt[j].intCnt+" ,Numeric:"+oCsv.statsCnt[j].realCnt+",Bit:"+oCsv.statsCnt[j].bitCnt+",Date:"+oCsv.statsCnt[j].dateCnt+",Empty:"+oCsv.statsCnt[j].emptyCnt}}
function flatOptions(oCsv){oCsv=oCsv||CSV;var stats=getCsvColLength(oCsv);var hdr=getCsvHeader(oCsv);var s="<table>\n<tr>\n<th>Col #</th><th>Field Name</th><th>Trim</th><th>Pad Size</th>";s+="<th>Upper</th><th>Lower</th><th>Right<br/>Justify</th><th>Center<br/>Justify</th></tr>";var template="<tr><td>{#}</td>";template+="<td>{FIELDNAME{#}}</td>\n";template+="<td><input type=checkbox id=\"ftrim{#}\" value=\"Y\" ></td>\n";template+="<td><input type=text id=\"fpadsize{#}\" size=3 maxlength=3 value=\"\" ></td>\n";template+="<td><input type=checkbox id=\"chkupper{#}\"  value=\"Y\" onclick=\"if(this.checked)document.getElementById('chklower{#}').checked=false\"></td>\n";template+="<td><input type=checkbox id=\"chklower{#}\"  value=\"Y\" onclick=\"if(this.checked)document.getElementById('chkupper{#}').checked=false\"></td>\n";template+="<td><input type=checkbox id=\"chkrjust{#}\"  value=\"Y\" onclick=\"if(this.checked)document.getElementById('chkcjust{#}').checked=false\"></td>\n";template+="<td><input type=checkbox id=\"chkcjust{#}\"  value=\"Y\" onclick=\"if(this.checked)document.getElementById('chkrjust{#}').checked=false\"></td>\n";template+="</tr>";var j;for(j=0;j<hdr.length;j++){s+=template.replace(/{#}/g,""+(j+1)).replace("{FIELDNAME"+(j+1)+"}",hdr[j].replace(/\s+/g,"_"))}
s+="</table>";return s}
function parseAndOptions(oCsv,forceOptions){var s;oCsv=oCsv||CSV;if(document.getElementById('txtRowLimit'))oCsv.limit=document.getElementById('txtRowLimit').value;if(document.getElementById('txt1'))CSV.parse(document.getElementById('txt1').value);if(document.getElementById('divOptions')&&(CSV.prevColumnsFound!=CSV.maxColumnsFound||forceOptions)){document.getElementById('divOptions').innerHTML=sqlOptions(CSV);setOptions(oCsv);CSV.prevColumnsFound=CSV.maxColumnsFound}
if(document.getElementById('divFlatOptions')&&(CSV.prevColumnsFound!=CSV.maxColumnsFound||forceOptions)){document.getElementById('divFlatOptions').innerHTML=flatOptions(CSV);CSV.prevColumnsFound=CSV.maxColumnsFound}
if(document.getElementById("divInputCounts")){document.getElementById("divInputCounts").innerHTML="Input Records- Header: "+(((CSV.arHeaderRow.length==0)&&(CSV.isFirstRowHeader))?"missing":CSV.isFirstRowHeader)+" &nbsp; &nbsp; "+" Separator: "+(CSV.delimiter=="\t"?"Tab":CSV.delimiter==" "?"Space":CSV.delimiter)+" &nbsp; &nbsp; "+" Fields: "+CSV.maxColumnsFound+" &nbsp; &nbsp; "+" Data Records: "+(CSV.dataRowsFound<=0?"0":CSV.dataRowsFound)}}
function clearAll(){var appendMode=false;if(document.getElementById('chkAppend'))appendMode=document.getElementById('chkAppend').checked;if(document.getElementById('sepAuto'))document.getElementById('sepAuto').checked=true;if(CSV){CSV.delimiter=",";CSV.autodetect=true}
if(document.getElementById('txt1'))document.getElementById('txt1').value="";if(!appendMode)if(document.getElementById('txta'))document.getElementById('txta').value="";if(document.getElementById('txtCols'))document.getElementById('txtCols').value="";if(!appendMode)if(document.getElementById('diva'))document.getElementById('diva').innerHTML="";if(document.getElementById('divOptions'))document.getElementById('divOptions').innerHTML="";if(document.getElementById('divFlatOptions'))document.getElementById('divFlatOptions').innerHTML="";parseAndOptions();setupSortDD()}
function getUserOptions(colpos){}
function radiovalue(radioObj){var j;if(!radioObj)return "";var radioLength=radioObj.length;if(radioLength==undefined)if(radioObj.checked){return radioObj.value}else{return ""}
for(var i=0;i<radioLength;i++){if(radioObj[i].checked){return radioObj[i].value}}
return ""}
function setRadioValue(radioObj,newValue){if(!radioObj)return;var radioLength=radioObj.length;if(radioLength==undefined){radioObj.checked=(radioObj.value==newValue.toString());return}
newValue=(newValue||"")+"";if(newValue==="\t")newValue="\\t";for(var i=0;i<radioLength;i++){radioObj[i].checked=false;if(radioObj[i].value==newValue){radioObj[i].checked=true}}}
function sortStr(){var ddFld;var a,d,j,s,t;s="";for(j=1;j<=4;j++){ddFld=document.getElementById('selSortFld'+j);if(!ddFld)continue;d=document.getElementById('selSortFld'+j).value;if(d=="")continue;t=document.getElementById('selSortType'+j).value;a=document.getElementById('selSortAsc'+j).value;if(j>1)s+=",";s+=t+d+a}
CSV.setSortFlds(s);CSV.mySortNeeded=true;return s}
function setupSortDD(){var dd;var j,k,o;for(j=1;j<=4;j++){dd=document.getElementById('selSortFld'+j);if(!dd)continue;if(dd.options.length-1==CSV.maxColumnsFound)break;dd.options.length=1;dd.selectedIndex=0;for(k=1;k<=CSV.maxColumnsFound;k++){o=document.createElement("option");o.text=o.value=""+k;dd.options.add(o)}}
sortStr();if(typeof(csvCreateQueryUI)==typeof(Function))csvCreateQueryUI();if(csvRedQuery)csvRedQuery.query=""}
function getFldPosArr(oCsv){var a=[];var i;oCsv=oCsv||CSV;if(oCsv.displayPoss!=""){a=oCsv.displayPoss.split(",");for(i=a.length-1;i>=0;i--){if(isNaN(a[i])||a[i]<1||a[i]>oCsv.maxColumnsFound){a.splice(i,1)}}}
if(a.length==0){for(i=0;i<oCsv.maxColumnsFound;i++){a[a.length]=i+1}}
if(a.length==0){for(i=0;i<oCsv.arHeaderRow.length;i++)a[a.length]=i+1}
return a}
function flattenSqlJson(data){var j;var newo=[];for(j=0;j<data.length;j++){var rec={};for(k=0;k<data[j].length;k++){rec[data[j][k].column]=data[j][k].value}
newo[j]=rec}
return newo}
function getExampleCsv(){var s="id,name,amount,Remark\n"+"1,\"Johnson, Smith, and Jones Co.\",345.33,Pays on time\n"+"2,\"Sam \"\"Mad Dog\"\" Smith\",993.44,\n"+"3,\"Barney & Company\",0,\"Great to work with\n"+"and always pays with cash.\"\n"+"4,Johnson's Automotive,2344,\n";return s}
function getExampleXml(n){n=(n||1)-1;var s="<?xml version=\"1.0\"?>\n"+"<ROWSET>\n"+"<ROW>\n"+"<id>1</id>\n"+"<name>Johnson, Smith, and Jones Co.</name>\n"+"<amount>345.33</amount>\n"+"<Remark>Pays on time</Remark>\n"+"</ROW>\n"+"<ROW>\n"+"<id>2</id>\n"+"<name>Sam &quot;Mad Dog&quot; Smith</name>\n"+"<amount>993.44</amount>\n"+"<Remark></Remark>\n"+"</ROW>\n"+"<ROW>\n"+"<id>3</id>\n"+"<name>Barney &amp; Company</name>\n"+"<amount>0</amount>\n"+"<Remark>Great to work with\n"+"and always pays with cash.</Remark>\n"+"</ROW>\n"+"<ROW>\n"+"<id>4</id>\n"+"<name>Johnson&apos;s Automotive</name>\n"+"<amount>2344</amount>\n"+"<Remark></Remark>\n"+"</ROW>\n"+"</ROWSET>";return s}
function getExampleJson(n){n=(n||1)-1;var s=["[\n"+"  {\n"+"    \"id\":1,"+"    \"name\":\"Johnson, Smith, and Jones Co.\",\n"+"    \"amount\":345.33,"+"    \"Remark\":\"Pays on time\"\n"+"  },\n"+"  {\n"+"    \"id\":2,"+"    \"name\":\"Sam \\\"Mad Dog\\\" Smith\",\n"+"    \"amount\":993.44,"+"    \"Remark\":\"\"\n"+"  },\n"+"  {\n"+"    \"id\":3,"+"    \"name\":\"Barney & Company\",\n"+"    \"amount\":0,"+"    \"Remark\":\"Great to work with\\nand always pays with cash.\"\n"+"  },\n"+"  {\n"+"    \"id\":4,"+"    \"name\":\"Johnson's Automotive\",\n"+"    \"amount\":2344,"+"    \"Remark\":\"\"\n"+"  }\n"+"]\n","{ \"data\" : [\n"+"  {"+"    \"id\":1,"+"    \"name\":\"Johnson, Smith, and Jones Co.\""+"  },\n"+"  {"+"    \"id\":2,"+"    \"name\":\"Sam \\\"Mad Dog\\\" Smith\""+"  },\n"+"  {"+"    \"id\":3,"+"    \"name\":\"Barney & Company\""+"  },\n"+"  {"+"    \"id\":4,"+"    \"name\":\"Johnson's Automotive\""+"  }\n"+"] }\n","{ \"race\" : \n"+" { \"entries\" : [\n"+"  {"+"    \"id\":11,"+"    \"name\":\"Johnson, Smith, and Jones Co.\""+"  },\n"+"  {"+"    \"id\":22,"+"    \"name\":\"Sam \\\"Mad Dog\\\" Smith\""+"  },\n"+"  {"+"    \"id\":33,"+"    \"name\":\"Barney & Company\""+"  },\n"+"  {"+"    \"id\":44,"+"    \"name\":\"Johnson's Automotive\""+"  }\n"+"] }\n}\n","{\n"+"    \"id\":1,"+"    \"name\":\"Johnson, Smith, and Jones Co.\","+"    \"amount\":345.33,"+"    \"Remark\":\"Pays on time\"\n"+"}\n","[\n"+"    ["+"      1,"+"      \"Johnson, Smith, and Jones Co.\","+"      345.33"+"    ],\n"+"    ["+"      99,"+"      \"Acme Food Inc.\","+"      2993.55"+"    ]\n"+"]"];return s[n]}
function getExampleKml(){var s="National Park,$ Obligated,State,Latitude,Longitude\n"+"Abraham Lincoln Birthplace NHS,\"$34,584\",KY,37.6116333423,-85.6442940021\n"+"Acadia,\"$102,631\",ME,44.3593807753,-68.2397319808\n"+"Andersonville,\"$65,133\",GA,32.197905290823,-84.1302615685733\n"+"Andrew Johnson ,\"$17,949\",TN,36.1562449930463,-82.8370902853041\n"+"Antietam,\"$54,743\",MD,39.462381614,-77.7359854016\n"+"Appomattox Court House,\"$12,651\",VA,37.3826448073,-78.8027430409\n"+"Assateague Island,\"$51,921\",MD,38.0556022623662,-75.2453836072023\n"+"Big Bend,\"$535,983\",TX,29.0103562389,-103.311115521\n"+"Big South Fork National River and Recreation Area,\"$3,009\",\"TN, KY\",36.3837375235,-84.6743069824\n";return s}
function getExampleFlat(){var s="1     Johnson, Smith, and Jones Co.  345.33     Pays on time                  \n"+"2     Sam \"Mad Dog\" Smith            993.44              \n"+"3     Barney & Company               0          Great to work with and always pays with cash.      \n"+"4     Johnson's Automotive           2344        \n";return s}
function getExampleGeoJson(n){var s='{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[-85.6442940021,37.6116333423]},\"properties\":{\"National Park\":\"Abraham Lincoln Birthplace NHS\",\"$ Obligated\":\"$34,584\",\"State\":\"KY\"}},{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[-68.2397319808,44.3593807753]},\"properties\":{\"National Park\":\"Acadia\",\"$ Obligated\":\"$102,631\",\"State\":\"ME\"}},{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[-84.1302615685733,32.197905290823]},\"properties\":{\"National Park\":\"Andersonville\",\"$ Obligated\":\"$65,133\",\"State\":\"GA\"}},{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[-82.8370902853041,36.1562449930463]},\"properties\":{\"National Park\":\"Andrew Johnson \",\"$ Obligated\":\"$17,949\",\"State\":\"TN\"}},{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[-77.7359854016,39.462381614]},\"properties\":{\"National Park\":\"Antietam\",\"$ Obligated\":\"$54,743\",\"State\":\"MD\"}},{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[-78.8027430409,37.3826448073]},\"properties\":{\"National Park\":\"Appomattox Court House\",\"$ Obligated\":\"$12,651\",\"State\":\"VA\"}},{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[-75.2453836072023,38.0556022623662]},\"properties\":{\"National Park\":\"Assateague Island\",\"$ Obligated\":\"$51,921\",\"State\":\"MD\"}},{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[-103.311115521,29.0103562389]},\"properties\":{\"National Park\":\"Big Bend\",\"$ Obligated\":\"$535,983\",\"State\":\"TX\"}},{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[-84.6743069824,36.3837375235]},\"properties\":{\"National Park\":\"Big South Fork National River and Recreation Area\",\"$ Obligated\":\"$3,009\",\"State\":\"TN, KY\"}}]}';return s}
function loadScript(url){var s=document.createElement("script");s.type="text/javascript";s.id="dynScriptTemp";s.src=url;document.getElementsByTagName("head")[0].appendChild(s)}
function loadScriptAndRun(url){if(!url.startsWith('?')){url='?'+url}
loadScript("http://www.ddginc-usa.com/cgi-bin/url-to-json.php"+url)}
function loadDataAndRun(data){document.getElementById('txt1').value=data.html.join("\n");document.getElementById('btnRun').click()}
function loadURL(url){if(url.trim()==""){alert("Missing URL");return false}
loadScriptAndRun("?callback=loadDataAndRun&url="+encodeURIComponent(url))}
function prettyJSON(text,step){var step=step?step:3;if(typeof JSON==='undefined')return text;try{if(typeof text==="string")return JSON.stringify(JSON.parse(text),null,step);if(typeof text==="object")return JSON.stringify(text,null,step)}catch(e){}
return text}
function getJsonLevel(o){if(typeof o==="string"){o=JSON.parse(o)}
var s=JSON.stringify(o,null,"\t").split(/\r\n|\n|\r/gm);var level=0;var j,a;for(j=0;j<s.length;j++){if(s[j].charAt(0)!="\t")continue;a=s[j].match(/\t+/gm);if(a[0].length>level)level=a[0].length}
return level+1}
function saveOutput(text,fn,doctype){var blob=new Blob([text],{type:"text/plain;charset=utf-8"});saveAs(blob,fn)}
function saveFile(text,ext){var fn=document.getElementById('fn').value.trim();if(fn==""){fn=document.getElementById('fn').value="convertcsv"}
var v=text.replace(/\r\n|\r|\n/gm,"\r\n");saveOutput(v,fn+"."+ext,null)}
function loadCsv(){if(!storageSup.has_html5_storage())return;if(document.getElementById('txt1')&&sessionStorage.getItem("clearPressed")!="Y"){assignText(storageSup.getCsv())}
sessionStorage.setItem("clearPressed","")}
function saveCsv(){if(!storageSup.has_html5_storage())return;}
function doTransformations(v,k,oCsv){if(document.getElementById("ftrim"+(k+1)))
if(document.getElementById("ftrim"+(k+1)).checked)v=v.trim();if(document.getElementById("ftriml"+(k+1)))
if(document.getElementById("ftriml"+(k+1)).checked)v=v.ltrim();if(document.getElementById("ftrimr"+(k+1)))
if(document.getElementById("ftrimr"+(k+1)).checked)v=v.rtrim();if(document.getElementById("chkupper"+(k+1)))
if(document.getElementById("chkupper"+(k+1)).checked)v=v.toUpperCase();if(document.getElementById("chklower"+(k+1)))
if(document.getElementById("chklower"+(k+1)).checked)v=v.toLowerCase();if(document.getElementById("chkcap"+(k+1)))
if(document.getElementById("chkcap"+(k+1)).checked)v=v.capitalize();if(document.getElementById("chkpunct"+(k+1)))
if(document.getElementById("chkpunct"+(k+1)).checked){if(oCsv.statsCnt[k]){if(oCsv.statsCnt[k].fieldType!="N"&&oCsv.statsCnt[k].fieldType!="I")v=v.removePunctuation()}else{v=v.removePunctuation()}}
if(document.getElementById("chkcrunch"+(k+1)))
if(document.getElementById("chkcrunch"+(k+1)).checked)v=v.crunch();return v}